package org.nick124;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;

/**
 * Backing class for CreateProjectUI.form (IntelliJ GUI Designer).
 * The $$$setupUI$$$ / $$$getRootComponent$$$ methods below mirror what
 * the IDE would normally generate from the .form file; if you open this
 * file in IntelliJ with the form bound, the designer will regenerate them.
 */
public class CreateProjectUI {

    private JPanel rootPanel;
    private JLabel projectNameLabel;
    private JTextField projectNameField;
    private JLabel locationLabel;
    private JTextField locationField;
    private JButton browseButton;
    private JLabel projectTypeLabel;
    private JComboBox<String> projectTypeCombo;
    private JButton createButton;
    private JButton cancelButton;

    /**
     * @wbp.parser.entryPoint
     */
    public CreateProjectUI() {
        $$$setupUI$$$();

        // Default location: user's home directory
        locationField.setText(System.getProperty("user.home") + File.separator + "IdeaProjects");

        browseButton.addActionListener(e -> onBrowse());
        createButton.addActionListener(e -> onCreate());
        cancelButton.addActionListener(e -> onCancel());
    }

    private void onBrowse() {
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        File current = new File(locationField.getText());
        if (current.exists()) {
            chooser.setCurrentDirectory(current);
        }
        int result = chooser.showOpenDialog(rootPanel);
        if (result == JFileChooser.APPROVE_OPTION) {
            locationField.setText(chooser.getSelectedFile().getAbsolutePath());
        }
    }

    private void onCreate() {
        String name = projectNameField.getText().trim();
        String location = locationField.getText().trim();
        String type = (String) projectTypeCombo.getSelectedItem();

        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(rootPanel,
                    "Please enter a project name.",
                    "Missing Project Name",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        File projectDir = new File(location, name);
        if (!projectDir.exists() && !projectDir.mkdirs()) {
            JOptionPane.showMessageDialog(rootPanel,
                    "Could not create project directory:\n" + projectDir.getAbsolutePath(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        JOptionPane.showMessageDialog(rootPanel,
                "Created " + type + " project \"" + name + "\" at:\n" + projectDir.getAbsolutePath(),
                "Project Created",
                JOptionPane.INFORMATION_MESSAGE);
        
        GUI.getInstance().setFile(projectDir);
        
        Window window = SwingUtilities.getWindowAncestor(rootPanel);
        if (window != null) {
        	window.dispose();
        }
    }

    private void onCancel() {
        Window window = SwingUtilities.getWindowAncestor(rootPanel);
        if (window != null) {
            window.dispose();
        }
    }

    public JPanel getRootComponent() {
        return rootPanel;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer.
     * Builds the UI layout described in CreateProjectUI.form.
     * DO NOT edit this method by hand; regenerate via the UI Designer instead.
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridBagLayout());
        rootPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

        projectNameLabel = new JLabel("Project Name:");
        GridBagConstraints gbc_projectNameLabel = new GridBagConstraints();
        gbc_projectNameLabel.insets = new Insets(4, 4, 4, 4);
        gbc_projectNameLabel.anchor = GridBagConstraints.WEST;
        gbc_projectNameLabel.gridx = 0;
        gbc_projectNameLabel.gridy = 0;
        rootPanel.add(projectNameLabel, gbc_projectNameLabel);

        projectNameField = new JTextField();
        GridBagConstraints gbc_projectNameField = new GridBagConstraints();
        gbc_projectNameField.insets = new Insets(4, 4, 4, 4);
        gbc_projectNameField.fill = GridBagConstraints.HORIZONTAL;
        gbc_projectNameField.weightx = 1.0;
        gbc_projectNameField.gridwidth = 2;
        gbc_projectNameField.gridx = 1;
        gbc_projectNameField.gridy = 0;
        rootPanel.add(projectNameField, gbc_projectNameField);

        locationLabel = new JLabel("Location:");
        GridBagConstraints gbc_locationLabel = new GridBagConstraints();
        gbc_locationLabel.insets = new Insets(4, 4, 4, 4);
        gbc_locationLabel.anchor = GridBagConstraints.WEST;
        gbc_locationLabel.gridx = 0;
        gbc_locationLabel.gridy = 1;
        rootPanel.add(locationLabel, gbc_locationLabel);

        locationField = new JTextField();
        GridBagConstraints gbc_locationField = new GridBagConstraints();
        gbc_locationField.insets = new Insets(4, 4, 4, 4);
        gbc_locationField.fill = GridBagConstraints.HORIZONTAL;
        gbc_locationField.weightx = 1.0;
        gbc_locationField.gridx = 1;
        gbc_locationField.gridy = 1;
        rootPanel.add(locationField, gbc_locationField);

        browseButton = new JButton("Browse...");
        GridBagConstraints gbc_browseButton = new GridBagConstraints();
        gbc_browseButton.insets = new Insets(4, 4, 4, 4);
        gbc_browseButton.gridx = 2;
        gbc_browseButton.gridy = 1;
        rootPanel.add(browseButton, gbc_browseButton);

        projectTypeLabel = new JLabel("Project Type:");
        GridBagConstraints gbc_projectTypeLabel = new GridBagConstraints();
        gbc_projectTypeLabel.insets = new Insets(4, 4, 4, 4);
        gbc_projectTypeLabel.anchor = GridBagConstraints.WEST;
        gbc_projectTypeLabel.gridx = 0;
        gbc_projectTypeLabel.gridy = 2;
        rootPanel.add(projectTypeLabel, gbc_projectTypeLabel);

        projectTypeCombo = new JComboBox<>(new String[]{"c++", "python", "Empty Project"});
        GridBagConstraints gbc_projectTypeCombo = new GridBagConstraints();
        gbc_projectTypeCombo.insets = new Insets(4, 4, 4, 4);
        gbc_projectTypeCombo.fill = GridBagConstraints.HORIZONTAL;
        gbc_projectTypeCombo.weightx = 1.0;
        gbc_projectTypeCombo.gridwidth = 2;
        gbc_projectTypeCombo.gridx = 1;
        gbc_projectTypeCombo.gridy = 2;
        rootPanel.add(projectTypeCombo, gbc_projectTypeCombo);

        JPanel buttonPanel = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        createButton = new JButton("Create");
        cancelButton = new JButton("Cancel");
        buttonPanel.add(createButton);
        buttonPanel.add(cancelButton);

        GridBagConstraints gbc_buttonPanel = new GridBagConstraints();
        gbc_buttonPanel.insets = new Insets(4, 4, 4, 4);
        gbc_buttonPanel.fill = GridBagConstraints.HORIZONTAL;
        gbc_buttonPanel.gridwidth = 3;
        gbc_buttonPanel.gridx = 0;
        gbc_buttonPanel.gridy = 4;
        rootPanel.add(buttonPanel, gbc_buttonPanel);
    }

    /**
     * Entry point for standalone testing of the dialog.
     */
    public static void main(String[] args) {
        GUI.getInstance().main(args);
    }
}